## student_es
server:
  port: 8085
spring:
  application:
    name: zhs-search
  data:
    elasticsearch:
      student:
        cluster-name: zhs-elasticsearch
        cluster-nodes: localhost:9300
es:
  student:
    rest:
      uris: http://localhost:9200,http://localhost:9200,http://localhost:9200
      connection-timeout: 3000
      socket-timeout: 3000
      connection-request-timeout: 3000